services:
  detect-proposal:
    build:
        context: ./backend
    restart: on-failure
    container_name: gnomonitoring-backend
    volumes:
      - ./backend/config.yaml:/app/config.yaml
      - ./backend/db/:/app/db/
    ports:
      - 8880:8888 #metrics
      - 8989:8989 #backend
    command: [ "./server", "--disable-report" ]

  frontend:
      build:
        context: ./panel
      container_name: gnomonitoring-frontend
      ports:
        - "9191:80"
      volumes:
        - ./panel/.env:/app/.env.local
      env_file:
        - ./panel/.env
      restart: unless-stopped