#!/usr/bin/env bash
# One-shot setup for the local Gno devnet (3 genesis validators + a 4th
# identity reserved for the Phase 2 "new validator via GovDAO" scenario).
#
# Safe to re-run: every step is idempotent and skips work that was already
# done (images already built, secrets/genesis/dev account already
# generated). To start from scratch, remove genesis.json, .env,
# genesis_balances.txt, config.toml, .gnokey-dev/ and the per-node
# validator*/ directories.
#
# Usage:
#   GNO_REPO_PATH=/path/to/gno ./bootstrap.sh
#
# GNO_REPO_PATH defaults to /home/louis/gno.
set -euo pipefail

cd "$(dirname "$0")"

GNO_REPO_PATH="${GNO_REPO_PATH:-/home/louis/gno}"
DOCKER_USER="$(id -u):$(id -g)"
NODES=(validator validator2 validator3 validator4)

# Local-only dev account, committed in .gnokey-dev/ for reproducibility.
# Used as the genesis "unrestricted" address (auth.unrestricted_addrs) so it
# can register valopers / submit GovDAO proposals without paying realm
# storage deposits during testing. See README.md for the mnemonic.
DEV_PASSPHRASE="devpassword123"

echo "==> [1/7] Building gno-validator:local, gno-contribs:local, gno-gnokey:local"
docker build --target gnoland     -t gno-validator:local "$GNO_REPO_PATH"
docker build --target gnocontribs -t gno-contribs:local  "$GNO_REPO_PATH"
docker build --target gnokey      -t gno-gnokey:local    "$GNO_REPO_PATH"

echo "==> [2/7] Generating node secrets"
for node in "${NODES[@]}"; do
  mkdir -p "$node/gnoland-data/secrets"
  if [ -f "$node/gnoland-data/secrets/priv_validator_key.json" ]; then
    echo "    -> $node (existing secrets, skipping)"
  else
    echo "    -> $node"
    docker run --rm --user "$DOCKER_USER" \
      -v "$PWD/$node/gnoland-data:/gnoroot/gnoland-data" \
      gno-validator:local secrets init
  fi
done

echo "==> [3/7] Generating shared base config.toml"
if [ -f config.toml ]; then
  echo "    -> config.toml (already exists, skipping)"
else
  docker run --rm --user "$DOCKER_USER" -v "$PWD:/work" -w /work \
    gno-validator:local config init -config-path config.toml
fi
for node in "${NODES[@]}"; do
  cp config.toml "$node/config.toml"
done

echo "==> [4/7] Extracting addresses / pubkeys / node IDs"
get_secret() {
  docker run --rm --user "$DOCKER_USER" \
    -v "$PWD/$1/gnoland-data:/gnoroot/gnoland-data" \
    gno-validator:local secrets get "$2" -raw
}

VALIDATOR_ADDR=$(get_secret validator validator_key.address)
VALIDATOR_PUBKEY=$(get_secret validator validator_key.pub_key)
VALIDATOR_NODEID=$(get_secret validator node_id.id)

VALIDATOR2_ADDR=$(get_secret validator2 validator_key.address)
VALIDATOR2_PUBKEY=$(get_secret validator2 validator_key.pub_key)
VALIDATOR2_NODEID=$(get_secret validator2 node_id.id)

VALIDATOR3_ADDR=$(get_secret validator3 validator_key.address)
VALIDATOR3_PUBKEY=$(get_secret validator3 validator_key.pub_key)
VALIDATOR3_NODEID=$(get_secret validator3 node_id.id)

VALIDATOR4_ADDR=$(get_secret validator4 validator_key.address)
VALIDATOR4_PUBKEY=$(get_secret validator4 validator_key.pub_key)
VALIDATOR4_NODEID=$(get_secret validator4 node_id.id)

echo "    validator   addr=$VALIDATOR_ADDR  node_id=$VALIDATOR_NODEID"
echo "    validator2  addr=$VALIDATOR2_ADDR  node_id=$VALIDATOR2_NODEID"
echo "    validator3  addr=$VALIDATOR3_ADDR  node_id=$VALIDATOR3_NODEID"
echo "    validator4  addr=$VALIDATOR4_ADDR  node_id=$VALIDATOR4_NODEID (phase2, not in genesis)"

echo "==> [5/7] Writing .env (P2P seed addresses)"
cat > .env <<EOF
# Generated by bootstrap.sh - peer addresses derived from each node's
# committed node_key.json. Re-generating secrets requires re-running
# bootstrap.sh to refresh these values.
SEEDS_VALIDATOR=${VALIDATOR2_NODEID}@validator2:26656,${VALIDATOR3_NODEID}@validator3:26656
SEEDS_VALIDATOR2=${VALIDATOR_NODEID}@validator:26656,${VALIDATOR3_NODEID}@validator3:26656
SEEDS_VALIDATOR3=${VALIDATOR_NODEID}@validator:26656,${VALIDATOR2_NODEID}@validator2:26656
SEEDS_VALIDATOR4=${VALIDATOR_NODEID}@validator:26656,${VALIDATOR2_NODEID}@validator2:26656,${VALIDATOR3_NODEID}@validator3:26656
EOF

echo "==> [6/7] Generating local dev account (gnokey)"
if [ -d .gnokey-dev/data ]; then
  echo "    -> .gnokey-dev (already exists, skipping)"
else
  printf '%s\n%s\n' "$DEV_PASSPHRASE" "$DEV_PASSPHRASE" | docker run --rm -i --user "$DOCKER_USER" \
    -v "$PWD/.gnokey-dev:/gnoroot/keybase" \
    gno-gnokey:local add -insecure-password-stdin -home /gnoroot/keybase dev
fi
DEV_ADDR=$(docker run --rm --user "$DOCKER_USER" -v "$PWD/.gnokey-dev:/gnoroot/keybase" \
  gno-gnokey:local list -home /gnoroot/keybase | sed -n 's/.*addr: \(g1[a-z0-9]*\).*/\1/p')
echo "    dev addr=$DEV_ADDR"

echo "==> [7/7] Generating genesis_balances.txt and genesis.json"
cat > genesis_balances.txt <<EOF
# Local devnet balances - throwaway accounts, generously funded for testing.
${VALIDATOR_ADDR}=10000000000000ugnot  # samourai-crew-1
${VALIDATOR2_ADDR}=10000000000000ugnot # samourai-crew-2
${VALIDATOR3_ADDR}=10000000000000ugnot # samourai-crew-3
${VALIDATOR4_ADDR}=10000000000000ugnot # samourai-crew-4 (phase2)
${DEV_ADDR}=10000000000000ugnot        # dev (unrestricted, .gnokey-dev)
EOF

if [ -f genesis.json ]; then
  echo "    -> genesis.json (already exists, skipping generation)"
else
  VALIDATOR1_ADDR="$VALIDATOR_ADDR" VALIDATOR1_PUBKEY="$VALIDATOR_PUBKEY" VALIDATOR1_NAME="samourai-crew-1" \
  VALIDATOR2_ADDR="$VALIDATOR2_ADDR" VALIDATOR2_PUBKEY="$VALIDATOR2_PUBKEY" VALIDATOR2_NAME="samourai-crew-2" \
  VALIDATOR3_ADDR="$VALIDATOR3_ADDR" VALIDATOR3_PUBKEY="$VALIDATOR3_PUBKEY" VALIDATOR3_NAME="samourai-crew-3" \
  UNRESTRICTED_ADDR="$DEV_ADDR" \
    ./generate-genesis.sh
fi

for node in "${NODES[@]}"; do
  cp genesis.json "$node/genesis.json"
done

echo ""
echo "Bootstrap complete. Start the devnet with: docker compose up -d"
