name: Deploy to prod

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd gnomonitoring
            docker compose pull
            docker compose up -d
